### ISSUE TITLE
登录不了

### ISSUE THREAD

**Issue by jackyon** [Zjmainstay/RegexTesterForMac#1]
hi, 我下载了这款mac工具，测试了下，貌似登录不上哦，弹出了个窗口，等了很久都没显示出登录内容页面

**Comment by Zjmainstay** [comment]
是的，如果要做用户登录，需要利用后端去模拟官方信息，比较麻烦。

目前支持正则测试和保存，保存后的链接，你在浏览器端存入自己用户就可以。
