### ISSUE TITLE
汉化的正则表达式工具匹配不到结果

### ISSUE THREAD

**Issue by newbigland** [Zjmainstay/RegexTesterForMac#3]
您好
最近用了下您汉化的regex101工具网页版和Mac版，发现了无法匹配结果，但英文原版可以匹配出结果，语言是python3，要匹配的字符串是个HTML结构，如下：
[归档.zip](https://github.com/Zjmainstay/RegexTesterForMac/files/2039015/default.zip)
选择的flag是global和single line ,正则表达式见附件
英文版可以匹配出6个结果，汉化版和Mac无法给出结果，请有空可否解决，谢谢。
网页里贴html会被浏览器解释，见附件。

**Comment by Zjmainstay** [comment]
应该是`\w`的兼容问题，这个版本没有兼容，你将它改成`[^<>]`吧

**Comment by newbigland** [comment]
thanks
