### ISSUE TITLE
UI error 

### ISSUE THREAD

**Issue by moonD4rk** [Zjmainstay/RegexTesterForMac#4]
os version: macOS Catalina  10.15.1

software version:  v2.0 base on regex101.com v2

sidebar is mirroring, download from the last release.

<img width="798" alt="Screen Shot 2019-12-10 at 20 01 18" src="https://user-images.githubusercontent.com/24284231/70527848-d8335880-1b87-11ea-9cb0-7e96764cb769.png">

**Comment by Zjmainstay** [comment]
why you got two title bar on the top? try reinstall it. If it can not solve your problem, please use the online website https://regex101.com

**Comment by moonD4rk** [comment]
ok, i will use the website version.

<img width="494" alt="Screen Shot 2019-12-12 at 13 32 29" src="https://user-images.githubusercontent.com/24284231/70685289-e4ccc380-1ce3-11ea-9bdb-da980a78f64b.png">

two title bar because enable `show tab bar` from `view`
